openapi: 3.0.0
info:
  title: Book API
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /api/books:
    get:
      tags:
        - Book
      summary: Get all books
      operationId: getBooks
      responses:
        '200':
          description: A list of books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BookListResponse'
              examples:
                example-1:
                  summary: A list of books
                  value:
                    - id: 1
                      title: 'The Great Gatsby'
                      isbn: '9780743273565'
                    - id: 2
                      title: '1984'
                      isbn: '9780451524935'
    post:
      tags:
        - Book
      summary: Add a new book
      operationId: addBook
      requestBody:
        description: Book to add
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookCreationRequest'
            examples:
              example-1:
                summary: A new book to add
                value:
                  title: 'To Kill a Mockingbird'
                  isbn: '9780061120084'
                  price: 15.99
                  publicationDate: '1960-07-11'
        required: true
      responses:
        '201':
          description: Book created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookDetailsResponse'
              examples:
                example-1:
                  summary: Book created response
                  value:
                    id: 3
                    title: 'To Kill a Mockingbird'
                    isbn: '9780061120084'
                    price: 15.99
                    publicationDate: '1960-07-11'
  /api/books/{bookId}:
    get:
      tags:
        - Book
      summary: Get a book by ID
      operationId: getBookById
      parameters:
        - in: path
          name: bookId
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: A single book
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookDetailsResponse'
              examples:
                example-1:
                  summary: A single book response
                  value:
                    id: 1
                    title: 'The Great Gatsby'
                    isbn: '9780743273565'
                    price: 10.99
                    publicationDate: '1925-04-10'
        '404':
          description: Book not found
    put:
      tags:
        - Book
      summary: Update an existing book
      operationId: updateBook
      parameters:
        - in: path
          name: bookId
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Book to update
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookUpdateRequest'
            examples:
              example-1:
                summary: Updated book information
                value:
                  title: 'The Great Gatsby - Revised Edition'
                  price: 12.99
                  publicationDate: '1925-04-10'
        required: true
      responses:
        '200':
          description: Book updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookDetailsResponse'
              examples:
                example-1:
                  summary: Book updated response
                  value:
                    id: 1
                    title: 'The Great Gatsby - Revised Edition'
                    isbn: '9780743273565'
                    price: 12.99
                    publicationDate: '1925-04-10'
        '404':
          description: Book not found
    delete:
      tags:
        - Book
      summary: Delete a book
      operationId: deleteBook
      parameters:
        - in: path
          name: bookId
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Book deleted
        '404':
          description: Book not found
  /api/books/isbn/{isbn}:
    get:
      tags:
        - Book
      summary: Get a book by ISBN
      operationId: getBookByIsbn
      parameters:
        - in: path
          name: isbn
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A single book
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookDetailsResponse'
              examples:
                example-1:
                  summary: A single book response by ISBN
                  value:
                    id: 2
                    title: '1984'
                    isbn: '9780451524935'
                    price: 9.99
                    publicationDate: '1949-06-08'
        '404':
          description: Book not found
components:
  schemas:
    BookDetailsResponse:
      $ref: './model-schema.yaml#/BookDetailsResponse'
    BookListResponse:
      $ref: './model-schema.yaml#/BookListResponse'
    BookCreationRequest:
      $ref: './model-schema.yaml#/BookCreationRequest'
    BookUpdateRequest:
      $ref: './model-schema.yaml#/BookUpdateRequest'
