name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build and publish a Docker image for ${{ github.repository }}
      uses: macbre/push-to-ghcr@v14
      with:
        image_name: ${{ github.repository }}
        github_token: ${{ secrets.PERM_TOKEN }}
